/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/fr1.glb -o src/components/Fracture.jsx -k -K -r public 
*/
import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Fracture(props) {
  const { nodes, materials } = useGLTF("/models/fr1.glb");
  const group = useRef();

  useEffect(() => {
    const groupWorldPosition = new THREE.Vector3();
    group.current.getWorldPosition(groupWorldPosition);

    group.current.children.forEach((mesh) => {
      mesh.originalPosition = mesh.position.clone();
      const meshWorldPosition = new THREE.Vector3();
      mesh.getWorldPosition(meshWorldPosition);

      mesh.directionVector = meshWorldPosition
        .clone()
        .sub(groupWorldPosition)
        .normalize();
    });
  });

  return (
    <group {...props} dispose={null} ref={group}>
      {/* <group name="Scene"> */}
      {/* <group name="Scene_Collection" />
        <group name="Sphere001" /> */}
      <mesh
        name="Sphere"
        geometry={nodes.Sphere.geometry}
        scale={[4.002, 4.018, 4.003]}
      >
        <meshToonMaterial color="springgreen" />
      </mesh>
      <mesh
        name="Sphere003"
        geometry={nodes.Sphere003.geometry}
        // material={nodes.Sphere003.material}
        scale={[4.002, 4.018, 4.003]}
      >
        {" "}
        <meshToonMaterial color="springgreen" />
      </mesh>
      <mesh
        name="Sphere004"
        geometry={nodes.Sphere004.geometry}
        // material={materials.Material}
        scale={[4.002, 4.018, 4.003]}
      >
        <meshToonMaterial color="springgreen" />
      </mesh>
      <mesh
        name="Sphere005"
        geometry={nodes.Sphere005.geometry}
        // material={nodes.Sphere005.material}
        scale={[4.002, 4.018, 4.003]}
      >
        {" "}
        <meshToonMaterial color="springgreen" />
      </mesh>
      <mesh
        name="Sphere002"
        geometry={nodes.Sphere002.geometry}
        // material={nodes.Sphere002.material}
        position={[-6.985, 4.56, -4.674]}
        scale={[4.002, 4.018, 4.003]}
      >
        {" "}
        <meshToonMaterial color="springgreen" />
      </mesh>
      <mesh
        name="Sphere_cell"
        geometry={nodes.Sphere_cell.geometry}
        // material={nodes.Sphere_cell.material}
        position={[1.046, 2.343, -2.956]}
      >
        {" "}
        <meshToonMaterial color="springgreen" />
      </mesh>
      <mesh
        name="Sphere_cell001"
        geometry={nodes.Sphere_cell001.geometry}
        material={nodes.Sphere_cell001.material}
        position={[-2.656, 0.542, -2.621]}
      />
      <mesh
        name="Sphere_cell002"
        geometry={nodes.Sphere_cell002.geometry}
        material={nodes.Sphere_cell002.material}
        position={[3.71, 0.828, 0.508]}
      />
      <mesh
        name="Sphere_cell003"
        geometry={nodes.Sphere_cell003.geometry}
        material={nodes.Sphere_cell003.material}
        position={[0.737, -2.627, 2.772]}
      />
      <mesh
        name="Sphere_cell004"
        geometry={nodes.Sphere_cell004.geometry}
        material={nodes.Sphere_cell004.material}
        position={[3.155, -0.779, -2.201]}
      />
      <mesh
        name="Sphere_cell005"
        geometry={nodes.Sphere_cell005.geometry}
        material={nodes.Sphere_cell005.material}
        position={[3.323, 0.266, -1.966]}
      />
      <mesh
        name="Sphere_cell006"
        geometry={nodes.Sphere_cell006.geometry}
        material={nodes.Sphere_cell006.material}
        position={[-1.905, -0.496, -3.464]}
      />
      <mesh
        name="Sphere_cell007"
        geometry={nodes.Sphere_cell007.geometry}
        material={nodes.Sphere_cell007.material}
        position={[-0.806, 1.163, -0.644]}
      />
      <mesh
        name="Sphere_cell008"
        geometry={nodes.Sphere_cell008.geometry}
        material={nodes.Sphere_cell008.material}
        position={[0.382, -3.787, 0.516]}
      />
      <mesh
        name="Sphere_cell009"
        geometry={nodes.Sphere_cell009.geometry}
        material={nodes.Sphere_cell009.material}
        position={[-3.84, -0.692, 0.25]}
      />
      <mesh
        name="Sphere_cell012"
        geometry={nodes.Sphere_cell012.geometry}
        material={nodes.Sphere_cell012.material}
        position={[2.477, 2.993, 0.703]}
      />
      <mesh
        name="Sphere_cell013"
        geometry={nodes.Sphere_cell013.geometry}
        material={nodes.Sphere_cell013.material}
        position={[-1.216, -3.455, -1.257]}
      />
      <mesh
        name="Sphere_cell014"
        geometry={nodes.Sphere_cell014.geometry}
        material={nodes.Sphere_cell014.material}
        position={[-2.353, -0.952, 2.953]}
      />
      <mesh
        name="Sphere_cell015"
        geometry={nodes.Sphere_cell015.geometry}
        material={nodes.Sphere_cell015.material}
        position={[-3.679, -0.257, 1.202]}
      />
      <mesh
        name="Sphere_cell018"
        geometry={nodes.Sphere_cell018.geometry}
        material={nodes.Sphere_cell018.material}
        position={[0.162, -0.159, -3.879]}
      />
      <mesh
        name="Sphere_cell019"
        geometry={nodes.Sphere_cell019.geometry}
        material={nodes.Sphere_cell019.material}
        position={[0.484, 2.955, -2.386]}
      />
      <mesh
        name="Sphere_cell020"
        geometry={nodes.Sphere_cell020.geometry}
        material={nodes.Sphere_cell020.material}
        position={[-3.557, 0.728, 0.301]}
      />
      <mesh
        name="Sphere_cell021"
        geometry={nodes.Sphere_cell021.geometry}
        material={nodes.Sphere_cell021.material}
        position={[-2.56, -2.722, 0.583]}
      />
      <mesh
        name="Sphere_cell022"
        geometry={nodes.Sphere_cell022.geometry}
        material={nodes.Sphere_cell022.material}
        position={[-3.452, 0.439, -1.749]}
      />
      <mesh
        name="Sphere_cell023"
        geometry={nodes.Sphere_cell023.geometry}
        material={nodes.Sphere_cell023.material}
        position={[0.441, 1.277, 1.369]}
      />
      <mesh
        name="Sphere_cell024"
        geometry={nodes.Sphere_cell024.geometry}
        material={nodes.Sphere_cell024.material}
        position={[1.309, -3.226, 1.667]}
      />
      <mesh
        name="Sphere_cell025"
        geometry={nodes.Sphere_cell025.geometry}
        material={nodes.Sphere_cell025.material}
        position={[-0.933, -2.17, 3.034]}
      />
      <mesh
        name="Sphere_cell027"
        geometry={nodes.Sphere_cell027.geometry}
        material={nodes.Sphere_cell027.material}
        position={[1.311, 1.268, 2.758]}
      />
      <mesh
        name="Sphere_cell028"
        geometry={nodes.Sphere_cell028.geometry}
        material={nodes.Sphere_cell028.material}
        position={[1.594, -3.455, -0.782]}
      />
      <mesh
        name="Sphere_cell029"
        geometry={nodes.Sphere_cell029.geometry}
        material={nodes.Sphere_cell029.material}
        position={[1.98, -3.372, 0.176]}
      />
      <mesh
        name="Sphere_cell030"
        geometry={nodes.Sphere_cell030.geometry}
        material={nodes.Sphere_cell030.material}
        position={[-0.428, 2.603, 2.842]}
      />
      <mesh
        name="Sphere_cell032"
        geometry={nodes.Sphere_cell032.geometry}
        material={nodes.Sphere_cell032.material}
        position={[2.636, -2.823, 0.806]}
      />
      <mesh
        name="Sphere_cell033"
        geometry={nodes.Sphere_cell033.geometry}
        material={nodes.Sphere_cell033.material}
        position={[-2.023, -2.361, 2.375]}
      />
      <mesh
        name="Sphere_cell035"
        geometry={nodes.Sphere_cell035.geometry}
        material={nodes.Sphere_cell035.material}
        position={[2.619, 1.173, 2.113]}
      />
      <mesh
        name="Sphere_cell036"
        geometry={nodes.Sphere_cell036.geometry}
        material={nodes.Sphere_cell036.material}
        position={[-1.304, 2.604, -2.745]}
      />
      <mesh
        name="Sphere_cell038"
        geometry={nodes.Sphere_cell038.geometry}
        material={nodes.Sphere_cell038.material}
        position={[-2.248, -2.032, -2.583]}
      />
      <mesh
        name="Sphere_cell039"
        geometry={nodes.Sphere_cell039.geometry}
        material={nodes.Sphere_cell039.material}
        position={[3.294, 1.234, -0.688]}
      />
      <mesh
        name="Sphere_cell040"
        geometry={nodes.Sphere_cell040.geometry}
        material={nodes.Sphere_cell040.material}
        position={[2.475, 2.248, -2.107]}
      />
      <mesh
        name="Sphere_cell041"
        geometry={nodes.Sphere_cell041.geometry}
        material={nodes.Sphere_cell041.material}
        position={[3.776, -0.466, 0.979]}
      />
      <mesh
        name="Sphere_cell042"
        geometry={nodes.Sphere_cell042.geometry}
        material={nodes.Sphere_cell042.material}
        position={[1.586, 3.453, -0.49]}
      />
      <mesh
        name="Sphere_cell043"
        geometry={nodes.Sphere_cell043.geometry}
        material={nodes.Sphere_cell043.material}
        position={[3.866, 0.473, -0.811]}
      />
      <mesh
        name="Sphere_cell044"
        geometry={nodes.Sphere_cell044.geometry}
        material={nodes.Sphere_cell044.material}
        position={[2.841, 2.47, 0.985]}
      />
      <mesh
        name="Sphere_cell045"
        geometry={nodes.Sphere_cell045.geometry}
        material={nodes.Sphere_cell045.material}
        position={[3.345, 0.695, 1.532]}
      />
      <mesh
        name="Sphere_cell047"
        geometry={nodes.Sphere_cell047.geometry}
        material={nodes.Sphere_cell047.material}
        position={[-1.97, 0.25, 3.172]}
      />
      <mesh
        name="Sphere_cell048"
        geometry={nodes.Sphere_cell048.geometry}
        material={nodes.Sphere_cell048.material}
        position={[-0.049, 3.875, -0.073]}
      />
      <mesh
        name="Sphere_cell049"
        geometry={nodes.Sphere_cell049.geometry}
        material={nodes.Sphere_cell049.material}
        position={[-2.64, 2.772, 0.913]}
      />
      <mesh
        name="Sphere_cell050"
        geometry={nodes.Sphere_cell050.geometry}
        material={nodes.Sphere_cell050.material}
        position={[1.702, -2.577, 2.43]}
      />
      <mesh
        name="Sphere_cell051"
        geometry={nodes.Sphere_cell051.geometry}
        material={nodes.Sphere_cell051.material}
        position={[2.856, -0.494, 2.582]}
      />
      <mesh
        name="Sphere_cell053"
        geometry={nodes.Sphere_cell053.geometry}
        material={nodes.Sphere_cell053.material}
        position={[-1.089, -0.799, -3.748]}
      />
      <mesh
        name="Sphere_cell055"
        geometry={nodes.Sphere_cell055.geometry}
        material={nodes.Sphere_cell055.material}
        position={[-1.477, 3.268, 1.328]}
      />
      <mesh
        name="Sphere_cell056"
        geometry={nodes.Sphere_cell056.geometry}
        material={nodes.Sphere_cell056.material}
        position={[2.065, 0.107, -3.325]}
      />
      <mesh
        name="Sphere_cell057"
        geometry={nodes.Sphere_cell057.geometry}
        material={nodes.Sphere_cell057.material}
        position={[0.152, 3.717, -1.333]}
      />
      <mesh
        name="Sphere_cell058"
        geometry={nodes.Sphere_cell058.geometry}
        material={nodes.Sphere_cell058.material}
        position={[1.391, -3.246, -1.54]}
      />
      <mesh
        name="Sphere_cell059"
        geometry={nodes.Sphere_cell059.geometry}
        material={nodes.Sphere_cell059.material}
        position={[1.694, -0.841, -3.491]}
      />
      <mesh
        name="Sphere_cell060"
        geometry={nodes.Sphere_cell060.geometry}
        material={nodes.Sphere_cell060.material}
        position={[2.729, -2.797, -0.491]}
      />
      <mesh
        name="Sphere_cell061"
        geometry={nodes.Sphere_cell061.geometry}
        material={nodes.Sphere_cell061.material}
        position={[-3.5, -1.2, 1.241]}
      />
      <mesh
        name="Sphere_cell062"
        geometry={nodes.Sphere_cell062.geometry}
        material={nodes.Sphere_cell062.material}
        position={[-3.597, -0.592, -1.1]}
      />
      <mesh
        name="Sphere_cell063"
        geometry={nodes.Sphere_cell063.geometry}
        material={nodes.Sphere_cell063.material}
        position={[-1.107, -2.67, -2.495]}
      />
      <mesh
        name="Sphere_cell064"
        geometry={nodes.Sphere_cell064.geometry}
        material={nodes.Sphere_cell064.material}
        position={[0.547, -3.902, -0.644]}
      />
      <mesh
        name="Sphere_cell065"
        geometry={nodes.Sphere_cell065.geometry}
        material={nodes.Sphere_cell065.material}
        position={[3.864, -0.275, -0.42]}
      />
      <mesh
        name="Sphere_cell066"
        geometry={nodes.Sphere_cell066.geometry}
        material={nodes.Sphere_cell066.material}
        position={[-0.662, -3.115, 2.105]}
      />
      <mesh
        name="Sphere_cell067"
        geometry={nodes.Sphere_cell067.geometry}
        material={nodes.Sphere_cell067.material}
        position={[1.491, -0.449, 3.545]}
      />
      <mesh
        name="Sphere_cell070"
        geometry={nodes.Sphere_cell070.geometry}
        material={nodes.Sphere_cell070.material}
        position={[2.699, 2.675, -0.721]}
      />
      <mesh
        name="Sphere_cell072"
        geometry={nodes.Sphere_cell072.geometry}
        material={nodes.Sphere_cell072.material}
        position={[-2.606, -1.988, 2.162]}
      />
      <mesh
        name="Sphere_cell073"
        geometry={nodes.Sphere_cell073.geometry}
        material={nodes.Sphere_cell073.material}
        position={[0.437, -3.302, -2.023]}
      />
      <mesh
        name="Sphere_cell074"
        geometry={nodes.Sphere_cell074.geometry}
        material={nodes.Sphere_cell074.material}
        position={[-1.455, 2.646, 2.512]}
      />
      <mesh
        name="Sphere_cell075"
        geometry={nodes.Sphere_cell075.geometry}
        material={nodes.Sphere_cell075.material}
        position={[3.451, -0.763, 1.703]}
      />
      <mesh
        name="Sphere_cell076"
        geometry={nodes.Sphere_cell076.geometry}
        material={nodes.Sphere_cell076.material}
        position={[-0.901, 0.64, -3.591]}
      />
      <mesh
        name="Sphere_cell077"
        geometry={nodes.Sphere_cell077.geometry}
        material={nodes.Sphere_cell077.material}
        position={[-1.714, 3.209, -1.03]}
      />
      <mesh
        name="Sphere_cell078"
        geometry={nodes.Sphere_cell078.geometry}
        material={nodes.Sphere_cell078.material}
        position={[-3.171, -0.354, 2.253]}
      />
      <mesh
        name="Sphere_cell079"
        geometry={nodes.Sphere_cell079.geometry}
        material={nodes.Sphere_cell079.material}
        position={[2.342, 0.326, 3.088]}
      />
      <mesh
        name="Sphere_cell080"
        geometry={nodes.Sphere_cell080.geometry}
        material={nodes.Sphere_cell080.material}
        position={[-2.629, 0.809, 1.936]}
      />
      <mesh
        name="Sphere_cell082"
        geometry={nodes.Sphere_cell082.geometry}
        material={nodes.Sphere_cell082.material}
        position={[-0.712, -3.8, -0.173]}
      />
      <mesh
        name="Sphere_cell085"
        geometry={nodes.Sphere_cell085.geometry}
        material={nodes.Sphere_cell085.material}
        position={[1.947, -2.785, 1.914]}
      />
      <mesh
        name="Sphere_cell086"
        geometry={nodes.Sphere_cell086.geometry}
        material={nodes.Sphere_cell086.material}
        position={[0.345, 0.345, 3.594]}
      />
      <mesh
        name="Sphere_cell087"
        geometry={nodes.Sphere_cell087.geometry}
        material={nodes.Sphere_cell087.material}
        position={[0.141, 3.665, 1.25]}
      />
      <mesh
        name="Sphere_cell090"
        geometry={nodes.Sphere_cell090.geometry}
        material={nodes.Sphere_cell090.material}
        position={[0.878, 3.245, 1.772]}
      />
      <mesh
        name="Sphere_cell010"
        geometry={nodes.Sphere_cell010.geometry}
        material={nodes.Sphere_cell010.material}
        position={[1.259, 1.153, -3.436]}
      />
      <mesh
        name="Sphere_cell011"
        geometry={nodes.Sphere_cell011.geometry}
        material={nodes.Sphere_cell011.material}
        position={[3.502, 1.714, 0.655]}
      />
      <mesh
        name="Sphere_cell016"
        geometry={nodes.Sphere_cell016.geometry}
        material={nodes.Sphere_cell016.material}
        position={[1.53, -0.883, 3.409]}
      />
      <mesh
        name="Sphere_cell017"
        geometry={nodes.Sphere_cell017.geometry}
        material={nodes.Sphere_cell017.material}
        position={[1.901, 1.41, -1.402]}
      />
      <mesh
        name="Sphere_cell026"
        geometry={nodes.Sphere_cell026.geometry}
        material={nodes.Sphere_cell026.material}
        position={[-1.638, -1.93, -3.107]}
      />
      <mesh
        name="Sphere_cell031"
        geometry={nodes.Sphere_cell031.geometry}
        material={nodes.Sphere_cell031.material}
        position={[-3.627, -1.603, 0.218]}
      />
      <mesh
        name="Sphere_cell034"
        geometry={nodes.Sphere_cell034.geometry}
        material={nodes.Sphere_cell034.material}
        position={[-2.169, -1.882, 2.679]}
      />
      <mesh
        name="Sphere_cell037"
        geometry={nodes.Sphere_cell037.geometry}
        material={nodes.Sphere_cell037.material}
        position={[0.833, 1.313, -2.106]}
      />
      <mesh
        name="Sphere_cell046"
        geometry={nodes.Sphere_cell046.geometry}
        material={nodes.Sphere_cell046.material}
        position={[-2.888, 2.689, 0.438]}
      />
      <mesh
        name="Sphere_cell052"
        geometry={nodes.Sphere_cell052.geometry}
        material={nodes.Sphere_cell052.material}
        position={[-0.773, -0.959, 3.652]}
      />
      <mesh
        name="Sphere_cell054"
        geometry={nodes.Sphere_cell054.geometry}
        material={nodes.Sphere_cell054.material}
        position={[1.365, 2.486, 2.6]}
      />
      <mesh
        name="Sphere_cell068"
        geometry={nodes.Sphere_cell068.geometry}
        material={nodes.Sphere_cell068.material}
        position={[-0.71, 1.172, 2.526]}
      />
      <mesh
        name="Sphere_cell069"
        geometry={nodes.Sphere_cell069.geometry}
        material={nodes.Sphere_cell069.material}
        position={[2.561, 2.271, 1.809]}
      />
      <mesh
        name="Sphere_cell071"
        geometry={nodes.Sphere_cell071.geometry}
        material={nodes.Sphere_cell071.material}
        position={[-1.25, 1.122, -1.588]}
      />
      <mesh
        name="Sphere_cell081"
        geometry={nodes.Sphere_cell081.geometry}
        material={nodes.Sphere_cell081.material}
        position={[-2.579, -0.89, -2.876]}
      />
      <mesh
        name="Sphere_cell083"
        geometry={nodes.Sphere_cell083.geometry}
        material={nodes.Sphere_cell083.material}
        position={[3.308, 2.006, -0.533]}
      />
      <mesh
        name="Sphere_cell084"
        geometry={nodes.Sphere_cell084.geometry}
        material={nodes.Sphere_cell084.material}
        position={[2.483, 1.28, -2.617]}
      />
      <mesh
        name="Sphere_cell088"
        geometry={nodes.Sphere_cell088.geometry}
        material={nodes.Sphere_cell088.material}
        position={[3.465, 1.631, 0.993]}
      />
      <mesh
        name="Sphere_cell089"
        geometry={nodes.Sphere_cell089.geometry}
        material={nodes.Sphere_cell089.material}
        position={[2.416, -0.971, 2.934]}
      />
      <mesh
        name="Sphere_cell091"
        geometry={nodes.Sphere_cell091.geometry}
        material={nodes.Sphere_cell091.material}
        position={[1.228, 1.349, -0.46]}
      />
      <mesh
        name="Sphere_cell092"
        geometry={nodes.Sphere_cell092.geometry}
        material={nodes.Sphere_cell092.material}
        position={[1.129, -2.429, -2.944]}
      />
      <mesh
        name="Sphere_cell093"
        geometry={nodes.Sphere_cell093.geometry}
        material={nodes.Sphere_cell093.material}
        position={[-3.234, -1.819, 1.188]}
      />
      <mesh
        name="Sphere_cell094"
        geometry={nodes.Sphere_cell094.geometry}
        material={nodes.Sphere_cell094.material}
        position={[-3.023, -2.169, -1.101]}
      />
      <mesh
        name="Sphere_cell095"
        geometry={nodes.Sphere_cell095.geometry}
        material={nodes.Sphere_cell095.material}
        position={[-3.573, 0.91, -0.916]}
      />
      <mesh
        name="Sphere_cell096"
        geometry={nodes.Sphere_cell096.geometry}
        material={nodes.Sphere_cell096.material}
        position={[-2.971, -1.245, 2.247]}
      />
      <mesh
        name="Sphere_cell097"
        geometry={nodes.Sphere_cell097.geometry}
        material={nodes.Sphere_cell097.material}
        position={[-0.945, 2.36, -3.102]}
      />
      {/* </group> */}
    </group>
  );
}

useGLTF.preload("/models/fr1.glb");
