/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/zatplanet1.glb -o src/components/Planet1.jsx -k -K -r public 
*/

import React from "react";
import { useGLTF, useTexture } from "@react-three/drei";

export function Planet1(props) {
  const { nodes, materials } = useGLTF("/models/zatplanet1.glb");
  const map = useTexture("public/textures/ganges_river_pebbles_diff_4k.png");
  const displacementMap = useTexture(
    "public/textures/ganges_river_pebbles_disp_4k.png"
  );
  const normalMap = useTexture(
    "public/textures/ganges_river_pebbles_nor_dx_4k.png"
  );
  const rougnessMap = useTexture(
    "public/textures/ganges_river_pebbles_rough_4k.png"
  );

  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="Scene_Collection" />
        <group name="planet" />
        <group name="Sphere001" />
        <mesh
          name="Sphere"
          geometry={nodes.Sphere.geometry}
          material={materials.Poliigon_GrassPatchyGround_4585_4K}
          scale={[4.002, 4.018, 4.003]}
        />
        <mesh
          name="Sphere003"
          geometry={nodes.Sphere003.geometry}
          material={materials.Poliigon_GrassPatchyGround_4585_4K}
          scale={[4.002, 4.018, 4.003]}
        />
        <mesh
          name="Sphere004"
          geometry={nodes.Sphere004.geometry}
          material={materials.Poliigon_GrassPatchyGround_4585_4K}
          scale={[4.002, 4.018, 4.003]}
        />
        <mesh
          name="Sphere005"
          geometry={nodes.Sphere005.geometry}
          material={materials.Poliigon_GrassPatchyGround_4585_4K}
          scale={[4.002, 4.018, 4.003]}
        />
        <mesh
          name="Sphere002"
          geometry={nodes.Sphere002.geometry}
          material={materials.Poliigon_GrassPatchyGround_4585_4K}
          position={[-6.985, 4.56, -4.674]}
          scale={[4.002, 4.018, 4.003]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/zatplanet1.glb");
